---
# vars file for linuxptp-host
#chrony_conf: "{{ '/etc/chrony/chrony.conf' if ansible_os_family == 'Debian' else '/etc/chrony.conf' }}"
#chrony_conf: '/etc/chrony.conf'
PTP_REPO_URL: 'http://git.code.sf.net/p/linuxptp/code'
PTP_PACKAGE_NAME: 'linuxptp'
PTP_PACKAGE_TAG: 'v3.1.1'
ALL_NICS: False
MANAGEMENT_IP_FOR_PTP: "{{ ansible_host }}"
time_server_IP: "{{ hostvars[ hank_name + '-time']['ansible_host'] }}"

lp_logrotate_confd:
  - path: ptp4l
    conf: |
      /var/log/ptp4l.log {
             daily
             rotate 7
             size 10M
             compress
             delaycompress
             copytruncate
             missingok
      }
  - path: phc2sys
    conf: |
      /var/log/phc2sys.log {
             daily
             rotate 7
             size 10M
             compress
             delaycompress
             copytruncate
             missingok
      }

lp_rsyslog_confd:
  - path: ptp4l
    conf: |
      if $programname == 'ptp4l' then /var/log/ptp4l.log
        & stop

  - path: phc2sys
    conf: |
      if $programname == 'phc2sys' then /var/log/phc2sys.log
        & stop

# This value(in seconds) is applied as a power of 2  for ptp4l logging interval
logging_summary_interval : 3 