---
# Create the base directories needed by Thanos
- name: Create Thanos Directories
  block:
      
    - name: "Create Thanos directories"
      file:
        path: "{{ base_install_dir }}/thanos/{{ item }}"
        state: directory
        recurse: yes
        owner: "{{ prom_user_name }}"
        group: "{{ prom_group_name }}"
      with_items:
        - [ "config" ]


    - name: "Create Thanos directories"
      file:
        path: "{{ base_data_dir }}/thanos/{{ item }}"
        state: directory
        recurse: yes
        owner: "{{ prom_user_name }}"
        group: "{{ prom_group_name }}"
      with_items:
        - [ "store", "compact" ]

  become: yes