---
# Central Compactor
# The Compactor MUST NOT be run anywhere except on the central metrics.
# https://github.com/thanos-io/thanos/blob/master/docs/components/compact.md
# Recommends 100GB disk space
- name: Control Thanos Compact Container
  become: yes
  community.docker.docker_container:
    state: "{{ thanos_compact_state }}"
    name: "{{ install_name }}_thanos_compact"
    network_mode: "{{ docker_network_name }}"
    image: quay.io/thanos/thanos:v0.14.0
    volumes:
      # Config files. Same as for Sidecar
      - "{{ base_install_dir }}/thanos/config/:/etc/thanos/"
      - "{{ base_data_dir }}/thanos/compact/tmp/:/tmp/thanos-compact"
    command:
      - 'compact'
      - '--wait'              # don't exit after compaction, wait and check for more 
      - '--wait-interval=5m'  # delay before checking for new compaction
      - '--data-dir="/tmp/thanos-compact"'
      - '--objstore.config-file=/etc/thanos/object_store_config.yml'
    restart_policy: always
    container_default_behavior: no_defaults 
    log_driver: json-file
    log_options:
      max-size: 1024m
