- name: Prior
  tags: worker_install
  become: true
  ansible.builtin.package:
    name: 
      - curl
    state: present

####################### FILEBEAT ##########################
# ansible-playbook site.yml --tags "filebeat" -v
###########################################################
# Check if Filebeat package is already downloaded

# > .rpm install for filebeat

- name: Check if Filebeat package exists CentOS
  tags: filebeat 
  stat: 
    path: /tmp/filebeat-{{ filebeat_version }}-x86_64.rpm
  register: r_filebeat_package_exist
  when: ansible_facts['distribution'] == "CentOS"

# Download Filebeat for CentOs
- name: Download Filebeat CentOS
  tags: filebeat
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-x86_64.rpm
    dest: /tmp/
  when:
    - ansible_facts['distribution'] == "CentOS"
    - r_filebeat_package_exist.stat.exists == false

# Install Filebeat using yum
- name: Install Filebeat CentOS
  tags: filebeat
  yum:
    name: /tmp/filebeat-{{ filebeat_version }}-x86_64.rpm
    state: present
  when: ansible_facts['distribution'] == "CentOS"

# > .deb install

- name: Check if Filebeat package exists Ubuntu
  tags: filebeat 
  stat: 
    path: /tmp/filebeat-{{ filebeat_version }}-amd64.deb
  register: d_filebeat_package_exist
  when: ansible_facts['distribution'] == "Ubuntu"

# Download Filebeat for Ubuntu
- name: Download Filebeat Ubuntu
  tags: filebeat
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-amd64.deb
    dest: /tmp/
  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - d_filebeat_package_exist.stat.exists == false
    
- name: Install Beat Ubuntu Prereq's
  tags: filebeat
  ansible.builtin.package:
    name: xz-utils
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"

  # Install Filebeat using apt
- name: Install Filebeat Ubuntu
  tags: filebeat
  ansible.builtin.package:
    deb: /tmp/filebeat-{{ filebeat_version }}-amd64.deb
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"


# normal run

- name: Install rsyslog
  tags: filebeat
  ansible.builtin.package:
    name: rsyslog
    state: present

# Copy the filebeat.yml 
- name: Copy Filebeat template file
  tags: filebeat
  template:
    src: "{{ filebeat_template_file }}"
    dest: /etc/filebeat/filebeat.yml

# Setup Filebeat
- name: Setup Filebeat
  tags: filebeat
  command: filebeat setup -e

# Start Filebeat
- name: Start Filebeat
  tags: filebeat
  service:
    name: filebeat
    state: restarted
    enabled: yes

####################### METRICBEAT ##########################
# ansible-playbook site.yml --tags "metricbeat" -v
#############################################################
# Check if metricbeat package is already downloaded

# > .rpm install for metricbeat

- name: Check if metricbeat package exists CentOS
  tags: metricbeat 
  stat: 
    path: /tmp/metricbeat-{{ metricbeat_version }}-x86_64.rpm
  register: r_metricbeat_package_exist
  when: ansible_facts['distribution'] == "CentOS"

# Download metricbeat for CentOs
- name: Download metricbeat CentOS
  tags: metricbeat
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{{ metricbeat_version }}-x86_64.rpm
    dest: /tmp/
  when:
    - ansible_facts['distribution'] == "CentOS"
    - r_metricbeat_package_exist.stat.exists == false
    

# Install metricbeat using yum
- name: Install metricbeat CentOS
  tags: metricbeat
  yum:
    name: /tmp/metricbeat-{{ metricbeat_version }}-x86_64.rpm
    state: present
  when: ansible_facts['distribution'] == "CentOS"

# > .deb install

- name: Check if metricbeat package exists Ubuntu
  tags: metricbeat 
  stat: 
    path: /tmp/metricbeat-{{ metricbeat_version }}-amd64.deb
  register: d_metricbeat_package_exist
  when: ansible_facts['distribution'] == "Ubuntu"

# Download metricbeat for Ubuntu
- name: Download metricbeat Ubuntu
  tags: metricbeat
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{{ metricbeat_version }}-amd64.deb
    dest: /tmp/
  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - d_metricbeat_package_exist.stat.exists == false
    

  # Install metricbeat using apt
- name: Install metricbeat Ubuntu
  tags: metricbeat
  ansible.builtin.package:
    deb: /tmp/metricbeat-{{ metricbeat_version }}-amd64.deb
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"


# normal run

# Copy the metricbeat.yml 
- name: Copy Metricbeat template file
  tags: metricbeat
  template:
    src: "{{ metricbeat_template_file }}"
    dest: /etc/metricbeat/metricbeat.yml

# Setup Metricbeat
- name: Setup Metricbeat
  tags: metricbeat
  command: metricbeat setup -e

# Start Metricbeat
- name: Start Metricbeat
  tags: metricbeat
  service:
    name: metricbeat
    state: restarted
    enabled: yes

####################### PACKETBEAT ##########################
# ansible-playbook site.yml --tags "packetbeat" -v
#############################################################
# Check if Packetbeat package is already downloaded
# > .rpm install for packetbeat

- name: Check if packetbeat package exists CentOS
  tags: packetbeat 
  stat: 
    path: /tmp/packetbeat-{{ packetbeat_version }}-x86_64.rpm
  register: r_packetbeat_package_exist
  when: ansible_facts['distribution'] == "CentOS"

# Download packetbeat for CentOs
- name: Download packetbeat CentOS
  tags: packetbeat
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-{{ packetbeat_version }}-x86_64.rpm
    dest: /tmp/
  when:
    - ansible_facts['distribution'] == "CentOS"
    - r_packetbeat_package_exist.stat.exists == false
    

# Install packetbeat using yum
- name: Install packetbeat CentOS
  tags: packetbeat
  yum:
    name: /tmp/packetbeat-{{ packetbeat_version }}-x86_64.rpm
    state: present
  when: ansible_facts['distribution'] == "CentOS"

# > .deb install

- name: Check if packetbeat package exists Ubuntu
  tags: packetbeat 
  stat: 
    path: /tmp/packetbeat-{{ packetbeat_version }}-amd64.deb
  register: d_packetbeat_package_exist
  when: ansible_facts['distribution'] == "Ubuntu"

# Download packetbeat for Ubuntu
- name: Download packetbeat Ubuntu
  tags: packetbeat
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-{{ packetbeat_version }}-amd64.deb
    dest: /tmp/
  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - d_packetbeat_package_exist.stat.exists == false

  # Install packetbeat using apt
- name: Install packetbeat Ubuntu
  tags: packetbeat
  ansible.builtin.package:
    deb: /tmp/packetbeat-{{ packetbeat_version }}-amd64.deb
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"

# normal run
# Copy the packetbeat.yml 
- name: Copy Packetbeat template file
  tags: packetbeat
  template:
    src: "{{ packetbeat_template_file }}"
    dest: /etc/packetbeat/packetbeat.yml

# Setup Packetbeat
- name: Setup Packetbeat
  tags: packetbeat
  command: packetbeat setup -e

# Start Packetbeat
- name: Start Packetbeat
  tags: packetbeat
  service:
    name: packetbeat
    state: restarted
    enabled: yes
