ansible_python_interpreter: python3


####################
#      Ports       #
####################
# In case we need to eliminate conficts
alertmanager_port: 9093    







prom_user_name: fab-prom
prom_group_name: fab-prom


docker_ipv6_subnet: fd8d:73ee:3857:1315::/64
docker_ipv6_gateway: fd8d:73ee:3857:1315::1


docker_network_name: "{{ install_name }}"
base_data_dir: "/opt/data/{{ install_name }}"
base_install_dir: "/opt/{{ install_name }}" 

# Mount of data drive only has to be done the first time a VM is setup
mount_data_drive: no
minio_username: fab_minio


minio_port: 9000
minio_console_port: 9099



####################
#     Grafana      #
####################

grafana_files_dir: files/Grafana
# grafana_plugin_files: 
#   - flant-statusmap-panel-v0.4.1.tar

grafana_templates_dir: templates/Grafana

grafana_cert:  "{{ host_cert }}"
grafana_key:  "{{ host_key }}"
grafana_user_name: grafana
grafana_user_id: 472
grafana_group_name: root  

grafana_datasource_template_files: 
  # Note can only use one default datasorce.
  #- grafana_local_prometheus_datasource.yml
  - grafana_thanos_datasource.yml


# TODO change these values
external_rack_label: odp
prometheus_name: {hostname}
      



####################
#    Prometheus    #
####################
prometheus_files_dir: files
prometheus_templates_dir: templates/Prometheus
        
prometheus_config_template_files: 
  - prometheus_config.yml

prometheus_config_files: []
  # need default var even if empty

prometheus_secrets: []


####################
#      NGINX       #
####################        

nginx_ip_ports:
  - 443:443  # grafana web page
  - 9090:9090     # prometheus stats
  #- 10902:10902   # thanos sidecar stats
  ##- 10901:10901 # thanos sidecar 
  - 9009:9009  # mimir
  
nginx_template_dir: templates/Nginx

nginx_server_confd_template_files: 
  - mimir.conf
  - prometheus_dual.conf
  - grafana_dual_web_sockets.conf
  #- thanos_sidecar_grpc.conf

nginx_config_template_files:
  - ssl_snippet.conf
  - nginx.conf

nginx_cert: "{{ host_cert }}"
nginx_key: "{{ host_key }}"
nginx_interm_cert: "{{ host_interm_cert }}"


