---
# Central Thanos - Store Gateway
- name: Control Thanos Store Container
  become: yes
  community.docker.docker_container:
    state: "{{ thanos_store_state }}"
    name: "{{ install_name }}_thanos_store"
    network_mode: "{{ docker_network_name }}"
    image: quay.io/thanos/thanos:v0.14.0
    volumes:
      # Config files. Same as for Sidecar
      - "{{ base_install_dir }}/thanos/config/:/etc/thanos/"
      # Map the node certs for TLS.
      - "{{ thanos_store_cert }}:/etc/thanos_certs/cert"
      - "{{ thanos_store_key }}:/etc/thanos_certs/key"
    container_default_behavior: no_defaults
    command:
      - 'store'
      - '--grpc-address=0.0.0.0:10911'
      - '--http-address=0.0.0.0:10912'
      - '--data-dir=/tmp/thanos/store'
      - '--objstore.config-file=/etc/thanos/object_store_config.yml'
      # Unfortunatly certs are needed since we have to use TLS everywhere for thanos :(
      - '--grpc-server-tls-cert=/etc/thanos_certs/cert' ##
      - '--grpc-server-tls-key=/etc/thanos_certs/key' ##
    ports:
      - "{{ thanos_store_ip }}:10911:10911"

    restart_policy: always


    # etc_hosts:
    #   "{{ thanos_extra_node_hosts  | default(omit) }}"

      