---
# Central Alertmanager
- name: Control Alertmanager Docker Container
  become: yes
  community.docker.docker_container:
    state: "{{ alertmanager_state }}"
    name: "{{ install_name }}_alertmanager"
    network_mode: "{{ docker_network_name }}"
    image: prom/alertmanager
    volumes:
      - "{{ base_install_dir }}/alertmanager/alertmanager_config.yml:/etc/alertmanager/alertmanager.yml"
      - "{{ base_install_dir }}/alertmanager/templates:/alertmanager/templates"
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--web.listen-address=:{{ alertmanager_port }}'
      - '--log.level=debug'
    # ports:
    #   - "{{ alertmanager_port }}:{{ alertmanager_port }}" 
    restart_policy: always
    container_default_behavior: no_defaults 

