---
# Ansible Galaxy Roles Requirements
# Must be installed using 
#   ansible-galaxy install -r requirements.yml
# and 
#   ansible-galaxy collection install -r requirements.yml


roles:
# Ensures pip is installed
  - name: geerlingguy.pip
  # #version: 

# Python Docker SDK to allow docker control from ansible.
  - name: geerlingguy.docker
  #version:

# For Node Exporters
  # cloudalchemy is already installed in os image
  - name: cloudalchemy.node_exporter
  #- name: prometheus.prometheus
  #version:

collections:
  - name: community.docker


