---
# Removes containers with the given names.      
- name: Remove Docker Containers
  community.docker.docker_container:
    state: absent
    name: "{{ install_name }}_{{ item }}"
  with_items: "{{ containers_to_act_on }}"
  become: yes