---
# Start-stop Grafana container
- name: Control Grafana Docker Container
  become: yes
  community.docker.docker_container:
    state: "{{ grafana_state }}"
    name: "{{ install_name }}_grafana"
    network_mode: "{{ docker_network_name }}"
    image: grafana/grafana:8.3.2
    user: "{{ grafana_user_name }}:{{ grafana_group_name }}"
    volumes:
      # data base dir
      - "{{ base_data_dir }}/grafana/data:/var/lib/grafana"
      # provisioning dirs for default datasources and dashboards  
      - "{{ base_install_dir }}/grafana/provisioning/:/etc/grafana/provisioning/"
      # plugin dirs 
      - "{{ base_install_dir }}/grafana/plugins/:/var/lib/grafana/plugins"
      # custom init settings dir
      - "{{ base_install_dir }}/grafana/custom:/etc/grafana/custom/"
      # Map the node certs for CiLogon TLS in  custom.ini.
      - "{{ grafana_cert }}:/etc/grafana/certs/cert:ro"
      - "{{ grafana_key }}:/etc/grafana/certs/key:ro"

    env_file: "{{ base_install_dir }}/grafana/env_file"
    # use nginx as tls proxy so no ports exposed here
    # ports:
    #    - 3000:3000
    container_default_behavior: no_defaults
    restart_policy: always
