---
# file: time_alert_rules.yml
# location: all racks

groups: 

- name: PTP Alerts
  rules: 
  
  - alert: RackNodeNotTimeSynced
    expr: node_timex_sync_status { component_type=~"head|worker" } == 0 
    for: 15m
    labels:
      severity: error
      fabric_system: time
      fabric_response: hardware
    annotations:
      summary:  "Time is not synced on node {{ $labels.instance }}"   
      description:  "node_timex_sync_status is 0 on {{ $labels.instance }}." 

  - alert: RackNodeTimexMaxErrorTooHigh
    expr: node_timex_maxerror_seconds{job="node", component_type=~"head|worker"} > 0.001
    for: 15m
    labels:
      severity: error
      fabric_system: time
      fabric_response: hardware
    annotations:
      summary:  "Timex max error exceeded on node {{ $labels.instance }}"   
      description:  "node_timex_maxerror_seconds is > 0.001 on {{ $labels.instance }}. Indicates node is not time synced." 

  - alert: RackGPSTimeUnknown
    expr: tmiGPSTimeKnown  == 0
    for: 15m
    labels:
      severity: error
      fabric_system: time
      fabric_response: hardware
    annotations:
      summary:  "GPS time is not known node {{ $labels.rack }}"   
      description:  "tmiGPSTimeKnown is 0 on {{ $labels.rack }}." 
      

  - alert: 2DGPSFix
    expr: tmiGPSFix == 1
    for: 15m
    labels:
      severity: info
      fabric_system: time
      fabric_response: hardware
    annotations:
      summary:  "GPS time sync is only 2D on {{ $labels.rack }}"   
      description:  "tmiGPSFix is 2 on {{ $labels.rack }}." 
      

  - alert: NoGPSFix
    expr: tmiGPSFix == 0
    for: 15m
    labels: 
      severity: warning
      fabric_system: time
      fabric_response: hardware
    annotations:
      summary:  "GPS time is not fixed on node {{ $labels.rack }}"   
      description:  "tmiGPSFix is 0 on {{ $labels.rack }}." 
      
