---
# file: vpn_ping_alert_rules.yml
# location: uky/renc racks

groups: 

- name: VPN Alerts
  rules:

  - alert: VPNPingFailed
    expr: probe_success {job="ping", reason="vpn"} == 0
    for: 5m
    labels:
      severity: warning
      fabric_system: vpn
      fabric_response: system
    annotations:
      summary:  "VPN ping to {{ $labels.instance }} failed for 1 minute."   
      description:  "{{ $labels.instance }} did not respond to ping for 1 minute." 

  - alert: VPNPingFailing
    expr: probe_success {job="ping", reason="vpn"} == 0
    for: 15m
    labels:
      severity: critical
      fabric_system: vpn 
      fabric_repsonse: system
    annotations:
      summary:  "VPN ping to {{ $labels.instance }} has failed for 15 minutes."   
      description:  "{{ $labels.instance }} has not responded to ping for more than 15 minutes." 
