---
# Global Thanos - Sidecar
- name: Control Thanos Sidecar
  become: yes
  community.docker.docker_container:
    state: "{{ thanos_sidecar_state }}"
    name: "{{ install_name }}_thanos_sidecar"
    network_mode: "{{ docker_network_name }}"
    # Exports Prometheus data to remote S3 compatible object store.
    image: quay.io/thanos/thanos:v0.14.0
    volumes:
      # config files
      - "{{ base_install_dir }}/thanos/config/:/etc/thanos/"
      # Provide access to the promtheus data.
      - "{{ base_data_dir }}/prometheus:/prometheus"
      # Map certs on head node.
      - "{{ thanos_sidecar_cert }}:/etc/thanos_certs/cert"
      - "{{ thanos_sidecar_key }}:/etc/thanos_certs/key"

    container_default_behavior: no_defaults
    
    command:
      - 'sidecar'
      - '--tsdb.path=/prometheus'
      - '--prometheus.url=http://{{ install_name }}_prometheus:9090'
      - '--grpc-address=0.0.0.0:10901'

      - '--grpc-server-tls-cert=/etc/thanos_certs/cert' 
      - '--grpc-server-tls-key=/etc/thanos_certs/key' 

      - '--http-address=0.0.0.0:10902'
      - '--objstore.config-file=/etc/thanos/object_store_config.yml'
    ports:
            - "{{ thanos_sidecar_ip }}:10901:10901"
    restart_policy: always
