---
# Blackbox Exporter
- name: Control Blackbox Exporter Docker Container
  become: yes 
  community.docker.docker_container:
    state: "{{ blackbox_state }}"
    name: "{{ install_name }}_blackbox"
    network_mode: "{{ docker_network_name }}"
    image: prom/blackbox-exporter
    #user: 
    volumes:
      # config files
      - "{{ base_install_dir }}/blackbox/config/:/config"
    command:
      - '--config.file=/config/blackbox.yml'
    #ports:
    #        - 9115:9115
    restart_policy: always
    container_default_behavior: no_defaults 