modules:

  icmp_ipv4:
    prober: icmp
    icmp:
      preferred_ip_protocol: "ip4" # defaults to "ip6"
      ip_protocol_fallback: false  # no fallback to "ip6"

  http_2xx:
    prober: http
    http:
      tls_config:
        insecure_skip_verify: true
      preferred_ip_protocol: "ip4" # defaults to "ip6"
      ip_protocol_fallback: false  # no fallback to "ip6"
      fail_if_ssl: false      # default
      fail_if_not_ssl: false  # default

  http_401:
    prober: http
    http:
      preferred_ip_protocol: "ip4" # defaults to "ip6"
      ip_protocol_fallback: false  # no fallback to "ip6"
      fail_if_ssl: false      # default
      fail_if_not_ssl: false  # default
      valid_status_codes: [401]
      
  dns_central_metrics_test:
    prober: dns
    timeout: 5s
    dns:
      query_name: metrics.fabric-testbed.net
      
  tcp_connect:
    prober: tcp
    http:
      tls_config:
        insecure_skip_verify: true
      preferred_ip_protocol: ip4
      ip_protocol_fallback: false
    tcp:
      tls: true
      tls_config:
        insecure_skip_verify: true
      preferred_ip_protocol: ip4
      ip_protocol_fallback: false
    timeout: 5s


  smtp_starttls:
    prober: tcp
    timeout: 5s
    http:
      preferred_ip_protocol: ip4
      ip_protocol_fallback: false
    tcp:
      tls_config:
        insecure_skip_verify: true
      preferred_ip_protocol: ip4
      ip_protocol_fallback: false
      query_response:
        - expect: "^220 ([^ ]+) ESMTP (.+)$"
        - send: "EHLO prober"
        - expect: "^250-STARTTLS"
        - send: "STARTTLS"
        - expect: "^220"
        - starttls: true
        - send: "EHLO prober"
        - expect: "^250-AUTH"
        - send: "QUIT"

