---
# Clones the fabric-deployment git repo so we can use the host and vars files.
# Note that the temp dir does not work in check mode

- hosts: localhost
  tasks:

  - name: Create local tmp directory
    tempfile: 
      state: directory 
      suffix: clone_dir
    register: tmp_clone_dir
  
  - name: show var
    debug:
      var: tmp_clone_dir
      #msg: "{{ temp_clone_dir }}"

  - name: Clone the fabric-deployment repository.
    git:
      #repo: https://github.com/fabric-testbed/fabric-deployment.git # This asks for username and password for every interaction with github - thus you have to type it all in 3 times
      repo: "git@github.com:fabric-testbed/fabric-deployment.git"  
      #version: monitoring
      # This just uses your ssh key
      dest: "{{ tmp_clone_dir.path }}"

  - name: Copy the needed dirs and files
    block:
      # - name: Create working dir
      #   file:
      #     path: ./hosts
      #     state: directory
      #   when: dir is absent??
      - name: Copy needed files.
        copy:
          src:  "{{ tmp_clone_dir.path }}/fabric-ansible/{{ item }}"
          dest: ./tmp_deployment_files/
          decrypt: no 

        with_items:
          - group_vars
          - host_vars
          - fabric-hosts
          #- monitoring

  - name: Remove the no longer needed fabric-deployment repository.
    file:
      path: "{{ tmp_clone_dir.path }}"
      state: absent
