---
# file: node_alert_rules.yml
# location: all racks, central

groups:

- name: Node Alerts
  rules:
  
  - alert: HostPhysicalComponentTooHot
    expr: node_hwmon_temp_celsius > 75
    for: 1m
    labels:
      severity: critical
      fabric_response: hardware
    annotations:
      summary: "{{ $externalLabels.rack }} Host physical component too hot (instance {{ $labels.instance }})"
      description: "{{ $externalLabels.rack }} Physical hardware component too hot\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: HostNodeOvertemperatureAlarm
    expr: node_hwmon_temp_crit_alarm_celsius == 1
    for: 0m
    labels:
      severity: critical
      fabric_response: hardware
    annotations:
      summary: "{{ $externalLabels.rack }} Host node overtemperature alarm (instance {{ $labels.instance }})"
      description: "{{ $externalLabels.rack }} Physical node temperature alarm triggered\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


  # Please add ignored mountpoints in node_exporter parameters like
  # "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run)($|/)".
  # Same rule using "node_filesystem_free_bytes" will fire when disk fills for non-root users.
  - alert: HostOutOfDiskSpace
    expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
    for: 2m
    labels:
      severity: warning
      fabric_response: hardware
    annotations:
      summary: "{{ $externalLabels.rack }} Host out of disk space (instance {{ $labels.instance }})"
      description: "{{ $externalLabels.rack }} Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  # Please add ignored mountpoints in node_exporter parameters like
  # "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run)($|/)".
  # Same rule using "node_filesystem_free_bytes" will fire when disk fills for non-root users.
  - alert: HostDiskWillFillIn24Hours
    expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) predict_linear(node_filesystem_avail_bytes{fstype!~"tmpfs"}[1h], 24 * 3600) < 0 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
    for: 2m
    labels:
      severity: warning
      fabric_response: hardware
    annotations:
      summary: "{{ $externalLabels.rack }} Host disk will fill in 24 hours (instance {{ $labels.instance }})"
      description: "{{ $externalLabels.rack }} Filesystem is predicted to run out of space within the next 24 hours at current write rate\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


  - alert: HostOutOfMemory
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
    for: 2m
    labels:
      severity: warning
      fabric_response: hardware
    annotations:
      summary: "{{ $externalLabels.rack }} Host out of memory (instance {{ $labels.instance }})"
      description: "{{ $externalLabels.rack }} Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


  - alert: HostHighCpuLoad
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
    for: 0m
    labels:
      severity: warning
      fabric_response: hardware
    annotations:
      summary: "{{ $externalLabels.rack }} Host high CPU load (instance {{ $labels.instance }})"
      description: "{{ $externalLabels.rack }} CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

