---
- block:
  - include_tasks: find_ptp_interfaces.yml
    loop: "{{ ansible_interfaces }}"
    loop_control:
      loop_var: IFACE
    become: True
  tags:
    - ptp_start
    - ptp_stop

- block:
  - include_tasks: for_vms.yml
    become: True
  tags: ptp_install


- block:
  - name: Stop phc2sys service for PTP Capable Interfaces
    systemd:
      state: stopped
      enabled: no
      name: phc2sys@{{ PTP_IFACE }}.service
    loop: "{{ PTP_IFACES + [ 'CLOCK_REALTIME' ] }}"
    loop_control:
      loop_var: PTP_IFACE
    ignore_errors: True
    become: True
  tags: ptp_stop


- block:
  - name: Start phc2sys service for PTP Capable Interfaces
    systemd:
      state: restarted
      enabled: yes
      name: phc2sys@{{ PTP_IFACE }}.service
    loop: "{{ PTP_IFACES + [ 'CLOCK_REALTIME' ] }}"
    loop_control:
      loop_var: PTP_IFACE
    ignore_errors: True
    become: True
  tags: ptp_start