---
# Docker Exporter
- name: Control Docker Exporter Docker Container
  become: yes
  community.docker.docker_container:
    state: "{{ docker_exporter_state }}"
    name: "{{ install_name }}_docker_exporter"
    network_mode: "{{ docker_network_name }}"
    image: prometheusnet/docker_exporter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: always
    container_default_behavior: no_defaults 
